### ISSUE TITLE
BEAMnrc hanging with multiple aperture BLOCK cutout

### ISSUE THREAD

**Issue by adeadrock** [nrc-cnrc/EGSnrc#280] opened 2017-05-01 23:56 UTC
I am trying to run an electron simulation with a somewhat complex cutout. I originally ran into an issue with some internal angles being greater than 180 degrees, so split the original polygon into multiple apertures. However, the simulation seems to hang without any obvious error message. Here is the cutout dimensions I am using:
~~~
5, # OF SUBREGIONS
12, NUMBER OF POINTS IN SUBREGION 1
3.38, 2.1, 
3.9, 5.06, 
3.65, 6.46, 
2.82, 7.79, 
1.9, 8.31, 
1.55, 8.38, 
-0.39, 8.36, 
-1.9, 7.92, 
-2.96, 6.78, 
-3.19, 6.31, 
-3.34, 4.56, 
-2.93, 3.22, 
5, NUMBER OF POINTS IN SUBREGION 2
3.22, 0.93, 
3.39, 1.51, 
3.38, 2.1, 
-2.93, 3.22, 
-2.9, 2.29, 
8, NUMBER OF POINTS IN SUBREGION 3
3.24, 0.15, 
3.22, 0.93, 
-2.9, 2.29, 
-3.23, 1.51, 
-3.43, 0.39, 
-3.23, -0.64, 
-2.7, -1.66, 
-2.07, -2.59, 
12, NUMBER OF POINTS IN SUBREGION 4
-0.32, -8.24, 
-0.04, -8.35, 
1.48, -8.44, 
2.22, -8.24, 
3.05, -7.31, 
3.7, -5.64, 
3.94, -4.63, 
3.96, -2.93, 
3.52, -0.81, 
3.24, 0.15, 
-2.07, -2.59, 
-1.6, -4.11, 
4, NUMBER OF POINTS IN SUBREGION 5
-1.6, -4.11, 
-1.36, -6.1, 
-1.0, -7.54, 
-0.32, -8.24,
~~~

I can sometimes get the simulation to run by changing the initial RNG seeds, but have tried changing multiple parameters of the BLOCK CM itself to no avail.

**Comment by adeadrock** [comment] 2017-05-02 03:56
After some experimenting this seems to be due to the fact that subregions 4 and 5 share the same start and end coordinates.

It runs without subregion 5 just fine, and runs if either of the x or y coordinates of the first or last points of either subregion is changed (i.e. changing the last point of subregion 5 to (-0.319, -8.24) results in a successful run).

**Comment by blakewalters** [comment] 2017-05-23 18:09
@adeadrock, would it be possible for you to provide the entire .egsinp file?

**Comment by blakewalters** [comment] 2024-08-27 17:21
@ftessier, @adeadrock: I'm unable to reproduce this using a 10 MeV e- beam incident on a block comprised of AL521ICRU with this cutout shape.  Pending more simulation details from @adeadrock, I suggest we archive this issue.

**Comment by ftessier** [comment] 2024-08-27 18:21
Closing since we cannot reproduce and have not received additional information. @adeadrock, please re-open if it remains an issue at your end.

**Closed by ftessier** 2024-08-27 18:21 UTC
