### ISSUE TITLE
DOSXYZnrc segmentation fault when compiled with -O0

### ISSUE THREAD

**Issue by packocrayons** [nrc-cnrc/EGSnrc#309] opened 2017-06-23 15:20 UTC
Running dosXYZnrc after compiling with -O0 causes a segfault immediately after printing the line "Photoelectron angular sampling OFF". It does not occur with any other optimisation (-O1, -O2, -O3). This occurs with an example file (EX16MVp) as well.

**Comment by blakewalters** [comment] 2017-08-01 13:59
Hi @packocrayons:
What system are you running on?

**Comment by crcrewso** [comment] 2017-08-01 17:16
I'd like to know the compiler version too. I have not yet seen a gcc -o0 related compile issue.

**Comment by DimitriosNikolopoulos** [comment] 2018-01-13 12:04
Hi all,
I am experiencing a SEGMENTATION FAULT in DOSXYZnrc in all x86_64 Fedora distributions (19,23) which I utilize. The gcc is (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6).

**Comment by blakewalters** [comment] 2024-08-27 16:37
@ftessier, @packocrayons: I'm unable to reproduce this issue on Mac OSX 14.5 with the current version of DOSXYZnrc.  Please confirm that this is still a problem on Fedora and, if not, let's close the issue.

**Comment by ftessier** [comment] 2024-08-27 18:20
I cannot reproduce this issue with `-O0` with `gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)` on the following linux distro:

```
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
```

I am therefore closing this issue. @packocrayons, don't hesitate to re-open if it remains an issue at your end.

**Closed by ftessier** 2024-08-27 18:20 UTC
