### ISSUE TITLE
beamnrc.egsinp corrupted after saving

### ISSUE THREAD

**Issue by RogerS0h** [nrc-cnrc/EGSnrc#312] opened 2017-07-13 05:09 UTC
I have correctly modelled a linac using BEAMnc. After saving the .egsinp file and exiting BEAMnrc GUI, the data of the CM of flatfilt is missing when reopened using BEAMnrc GUI. The data however, is present in the .egsinp file. Please advice

**Comment by blakewalters** [comment] 2017-08-01 14:01
Hi @RogerS0h 

Would it be possible for you to send your .egsinp file, or at least the portion of it relevant to FLATFILT?  Thanks!

**Comment by rtownson** [comment] 2018-10-03 15:45
I'm closing this issue for now since it could not be reproduced. @RogerS0h please let us know if you can provide more details.

**Closed by rtownson** 2018-10-03 15:45 UTC
