### ISSUE TITLE
egs++ simulation hangs when multiple BEAM sources reference same source phase space

### ISSUE THREAD

**Issue by vahx129** [nrc-cnrc/EGSnrc#108] opened 2016-06-20 16:05 UTC
egs_chamber hangs on a particular set of circumstances involving the source definition containing multiple BEAM simulation sources. 

In the example, a linear accelerator is modeled using an above jaws phase space and multiple BEAM simulations with dynamic jaws/MLC configurations which themselves results in below jaws phase spaces.

Ultimately, a patient treatment delivered to a chamber geometry could be simulated in egs_chamber using a weighted composite source consisting of the multiple BEAM simulations described above (with appropriate transformations). Each of those BEAM simulations themselves call upon the same Above Jaws phase space as a source of particles. 

The issue arises specifically when calling these multiple BEAM sources in an egs_chamber simulation. In isolation, each of the BEAM simulations runs perfectly fine. When multiple BEAM simulations are defined in the source definition of the egs_chamber input, the simulation will hang if the source being referenced is not the first BEAM source defined. For example, if the input file contains: 

:BEAM Source Definition 1: 
:BEAM Source Definition 2:
:BEAM Source Definition 3:
etc. 

and all 3 BEAM simulations call on the same above jaws phase space file as a source of particles, then the simulation will hang if the user calls on source 2 or source 3 in the egs_chamber simulation (or any composite source that requires source 2 and source 3). This is true even when the egs_chamber simulation calls for 1000 particles and the above jaws phase space contains well over 10 million.  

A temporary workaround to this issue was to duplicate the above jaws phase space into two files called phasespace_odds and phasespace_evens. The BEAM inputs were adjusted so that the referenced above jaws phase space was being alternated between every BEAM simulation defined in the input. While this did solve the issue on a personal installation of EGS, the issue manifested itself again when trying to do production runs on a parallel computing cluster. Under these circumstances, each parallel run created .egslog files which grew exponentially in size with the following repeated error message:

**WARNING** USED ALL PARTICLES FROM CHUNK IN SOURCE FILE!
               RESTARTING FROM FIRST PARTICLE IN THIS CHUNK.

This does specifically seem to be an issue with how egs++ handles multiple BEAM simulations which all make reference to the same above jaws phase space. 

If this is purely a user-specific error then I sincerely apologize but I can't think of any other obvious issues that I could be overlooking.

**Comment by vahx129** [comment] 2016-06-21 16:40
I wanted to clarify the issue a bit further as I've learned a bit more about it. The cause of the particles running out issue likely has to do with the following message seen in the log file of the run: 

One more details worth mentioning comes directly from the .egslst file from a hung run where multiple BEAM simulations were referencing the same above jaws phase space and showed the following message: 

READ PHASE SPACE INFORMATION FROM: 
Z:/MC Resources/Phase Spaces/VKD_6MV_AboveJaws_1e8.egsphsp1 

Phase space source already open. Will assume that 
DOSXYZnrc Source 20 is using this BEAM code as 
an initial geometry. Will not attempt to 
open phase space source.

This issue seems to have something to do with open file collisions which is why an odds/evens fix worked for a local run but still breaks down on a parallel computing cluster run. I hope that helps!

**Comment by marenaud** [comment] 2016-06-21 16:52
I think this bug is unrelated to egs++ in the sense that you can get the same bogus behaviour by running a DOSXYZnrc input file in shared-BEAM library mode where the particle source for the _BEAM_ accelerator is a phase space file. Runs fine in serial mode, and hangs with the same behaviour in parallel mode.

**Comment by vahx129** [comment] 2016-06-21 17:10
Maybe I'm not understanding the terminology properly but if this were strictly a serial mode issue, then shouldn't the local (non parallel cluster run) situation work fine? 

The chain of particle sources is (from top to bottom): 

Above Jaws Phase Space (1e8 particles) -> 9 Below Jaws BEAM simulations (1e7 particles) -> egs++ simulation (10,000 particles)

On a personal desktop installation (what I imagine to be serial) scenario, the simulation will still hang if for example BEAM sources 1 and 2 reference the same above jaws phase space. In that case, the log shows the aforementioned message about the phase space source already being open. In the local situation, I don't however receive the error in the .egslog about using up all of the particles. It just hangs and nothing further happens. The repeated error: WARNING USED ALL PARTICLES FROM CHUNK IN SOURCE FILE!
RESTARTING FROM FIRST PARTICLE IN THIS CHUNK. appears only in the parallel run log files but I imagine that it stems from the same issue.

If instead I duplicate the above jaws phase space on my local installation and make each subsequent BEAM source reference one phase space (odds) or the other (evens), then the local job runs quickly and with good looking results. 

So in essence my point of confusion is that if this were strictly a parallel run issue, then shouldn't local installations of EGS like one of my own that don't break up the jobs into multiple runs not have this issue with closing phase spaces at the end of simulations at all? 

Thanks for the feedback!

**Comment by marenaud** [comment] 2016-06-21 17:26
You're right, in my DOSXYZnrc case, the simulation ran fine in serial mode since the phase space was being accessed only once, but it failed in the parallel case due to the same bug you've encountered in parallel mode (the repeated error that you mention).

I don't think it the parallel bug stems from the same issue that you're facing when you try to use multiple BEAM sources with the same phase space file, though. In the parallel case, I think the logic for splitting particles from the phsp file between each job for the BEAM simulation is somehow wrong due to the fact that BEAM is being run as a shared library, and I can reproduce exactly the same error on DOSXYZnrc.

You've probably found the cause of your first bug with that error message in the egslst file where multiple beam accelerators are trying to access the same phsp file and some code won't let them.

**Comment by vahx129** [comment] 2016-06-21 17:47
Thanks for the clarification. So if we just stick to the issue as it pertains to a serial run and so as not to confuse multiple issues together, let me restate the issue like this then:

In an egs++ input file with a simple geometry (box), two (or potentially more) BEAM input sources are defined in the source definition block which both come from the same user BEAM linac. 

These BEAM input files are below jaws simulations of the user linac which both reference the same above jaws phase space as a source for particles. Both BEAM inputs run particles from this above jaws phase space through dynamic jaws/MLC. A single scoring plane is set below the mylar window CM which itself is just below the MLCs. Let's call the first one BEAM source 1 and the second BEAM source 2.

The issue occurs when BEAM source 2, or any later source is chosen as the simulation source. The issue is that the simulation will hang  right at the first batch and will remain hung even when running as few as 100 particles over several hours. The egsrun folder in the egs_chamber user code will not populate with any files under these circumstances.

In the user BEAM linac code folder, two egsrun folders do appear with .egslog and .egslist files which contain information.  BEAM source 1's  .egslog file shows that the phase space has been read with the following  information: 

FULL PHASE-SPACE TO BE READ FROM UNIT 42...
 INPUT NAME OF FILE WITH PHASE SPACE DATA(1 TO 80 CHARS,WITH .EXT)
 : 
 READ PHASE SPACE INFORMATION FROM: 
Z:/MC Resources/Phase Spaces/VKD_6MV_AboveJaws_1e8_Combined_Odds.egsphsp1       
          Phase space source with:
               Total number of particles =    722915887
                Number of photons =    662765371
                  Maximum particle kinetic energy =        6.050 MeV
                  Minimumelectron kinetic energy =        0.000 MeV
     # of particles incident from original source =   99998560.0

That same line in the .egslog of BEAM source 2 reports the following: 

FULL PHASE-SPACE TO BE READ FROM UNIT 42...
 INPUT NAME OF FILE WITH PHASE SPACE DATA(1 TO 80 CHARS,WITH .EXT)
 : 
 READ PHASE SPACE INFORMATION FROM: 
Z:/MC Resources/Phase Spaces/VKD_6MV_AboveJaws_1e8_Combined_Odds.egsphsp1       

 Phase space source already open.  Will assume that 
 DOSXYZnrc Source 20 is using this BEAM code as 
 an initial geometry.  Will not attempt to 
 open phase space source.

Beyond that, no further error messages, warnings, or fatal errors appear to be encountered. 
 
I think that's everything as it pertains to the issue surrounding a local run using egs_chamber with multiple BEAM sources that each rely on the same above jaws phase space. I hope this clarifies the issue exactly as it pertains to running this simple egs_chamber input on a serial system. 

It's worth mentioning again that a workaround for serial installs is to duplicate the above jaws phase space one time and point each subsequent BEAM source defined in the egs_chamber input file to either the odds or the evens phase space. So I believe this still qualifies as at least a minor bug with maybe larger implications for potential parallel runs in the future under similar circumstances. 

If this issue already exists elsewhere in different terms then I sincerely apologize for wasting anyone's time. Thanks!

**Comment by ftessier** [comment] 2016-06-21 18:00
Thank you for the detailed recap, and workaround, which will prove very useful when addressing the issue.

**Comment by rtownson** [comment] 2018-10-03 15:57
I believe this issue was fixed by PR #352.

**Closed by rtownson** 2018-10-03 15:57 UTC
