### ISSUE TITLE
EGSnrc installation failed

### ISSUE THREAD

**Issue by Wondesen** [nrc-cnrc/EGSnrc#208] opened 2016-12-05 04:07 UTC
I tried to install EGSnrc following the steps shown at https://github.com/nrc-cnrc/EGSnrc/wiki/install-EGSnrc-on-linux. 
At the last step, the EGSnrc installation failed. Error message line is 

doxyz_show.c:34:22:fatal error: xm/xmAll.h: No such file or Directory
Compilation terminated!
"Makefile:62:recipe for target '/home/-------/EGSnrc/HEN_HOUSE/bin/linux64/dosxyz_show' failed
Make: **[/home/------/EGSnrc/HEN_HOUSE/bin/linux64/dosxyz_show' failed]Error1
Compilation failed!

Using the information available at http://packages.ubuntu.com/, I discovered that the package libmotif-dev is missing. After installing the package, I installed EGSnrc successfully.

**Comment by rtownson** [comment] 2016-12-05 13:53
Duplicate of issue #166 - I'll add this to the wiki page now.

**Closed by rtownson** 2016-12-05 13:53 UTC

**Comment by ftessier** [comment] 2017-01-18 02:14
@rtownson thanks for adding this to the pre-requisites in the wiki. Can you add a small sub-section about obtaining libmotif-dev; perhaps just telling users to install that package on their favorite linux distribution, that it is a common package?
