### ISSUE TITLE
EDKnrc does not load the Mohan6 spectrum file

### ISSUE THREAD

**Issue by sahebeh** [nrc-cnrc/EGSnrc#493] opened 2018-11-02 20:32 UTC
hello every one. I am trying to calculate poly energy kernel using EDKnrc code. I tested the Mohan6 Spectrum (I think this spectrum is acceptable format for input file as said in pirs702 page31) in the input file. Unfortunately, the code can not  run this file. Thank you in advance for your guidance to solve this problem

**Comment by rtownson** [comment] 2018-11-22 13:37
Hi @sahebeh, I can't reproduce this issue. Double check that you used the full and correct path for the file. Did it give any meaningful errors? I expect the two lines should look like this:

```
INCIDENT ENERGY= spectrum
SPEC FILENAME=/home/yourUsername/EGSnrc/HEN_HOUSE/spectra/egsnrc/mohan6.spectrum
```

**Comment by sahebeh** [comment] 2018-11-26 14:22
Hello Dear Reid I changed the input file according to your instructions, which can be see as follow. But every time I get an error message, I took a print screen of run page and related error message  screen and attached it to you. Thanks really for your  great help.

RegardsTahereh Hadisi nia##########################:start source inputs:
#INCIDENT PARTICLE= photon          # electron,photon,positron

INCIDENT ENERGY= spectrum          # monoenergetic, spectrum;#INCIDENT KINETIC ENERGY(MEV)= 1.0 # only use for "monoenergetic" 
 If INCIDENT ENERGY= spectrum: SPEC FILENAME= C:\HEN_HOUSE\spectra\mohan6 SPEC IOUTSP= include            # none,include;                                   # none: no spectrum data in .egslst file                                   # include: output spectrum data to .egslst file 
SOURCE NUMBER= 1 # 0,1,2                 # 0: point source AT origin,   emission along Z-axis                 # 1: point source AT origin,   isotropically #radiating in 4Pi                 # 2: point source NEAR origin, emission along Z-axis
# ZIN= 0.000001  # only for source number 2                 # source offset on Z-axis                 # Option used to emulate old way of calculating EDK

:stop source inputs:#########################


    On Thursday, November 22, 2018, 5:07:56 PM GMT+3:30, Reid Townson <notifications@github.com> wrote:  
 
 
Hi @sahebeh, I can't reproduce this issue. Double check that you used the full and correct path for the file. Did it give any meaningful errors? I expect the two lines should look like this:
INCIDENT ENERGY= spectrum
SPEC FILENAME=/home/yourUsername/EGSnrc/HEN_HOUSE/spectra/egsnrc/mohan6.spectrum

**Comment by rtownson** [comment] 2018-11-26 15:13
It looks like you commented out the incident particle type. That is still necessary because the spectrum only provides the energies. I will close this issue because it is just a question - if you have follow-up questions please ask on the google+ community :)

```
:start source inputs:
INCIDENT PARTICLE= photon          # electron,photon,positron
INCIDENT ENERGY= spectrum     # monoenergetic, spectrum;
SPEC FILENAME=/home/yourUsername/EGSnrc/HEN_HOUSE/spectra/egsnrc/co60.spectrum
SOURCE NUMBER= 1
:stop source inputs:
```

**Closed by rtownson** 2018-11-26 15:13 UTC
Labels: question

**Comment by sahebeh** [comment] 2018-11-26 15:42
Dear Reidsorry for sending my question in wrong forum. I did your new guide about photon selection but the error still continue with same message error.
:start source inputs:
INCIDENT PARTICLE= photon          # electron,photon,positron

INCIDENT ENERGY= spectrum          # monoenergetic, spectrum;#INCIDENT KINETIC ENERGY(MEV)= 1.0 # only use for "monoenergetic" 
 If INCIDENT ENERGY= spectrum: SPEC FILENAME= C:\HEN_HOUSE\spectra\mohan6 SPEC IOUTSP= include            # none,include;                                   # none: no spectrum data in .egslst file                                   # include: output spectrum data to .egslst file 
SOURCE NUMBER= 1 # 0,1,2                 # 0: point source AT origin,   emission along Z-axis                 # 1: point source AT origin,   isotropically #radiating in 4Pi                 # 2: point source NEAR origin, emission along Z-axis
# ZIN= 0.000001  # only for source number 2                 # source offset on Z-axis                 # Option used to emulate old way of calculating EDK

:stop source inputs:#########################


Regards    On Monday, November 26, 2018, 6:44:14 PM GMT+3:30, Reid Townson <notifications@github.com> wrote:  
 
 
Closed #493.

**Comment by rtownson** [comment] 2018-11-26 17:06
It looks like you have mixed up the comments with the actual inputs. For example `SPEC FILENAME=` should be on its own line like it my example above. The text you pasted above is all mixed up, so try to clean it up, remove the comments if necessary, until it looks like my example.

Also, your path to the mohan6 file does not look correct, and it should have a file extension.

**Comment by sahebeh** [comment] 2018-11-26 20:00
Dear Reid
Thanks in advance for your kind help. I changed input file as follow:

:start source inputs:
INCIDENT PARTICLE= photon          # electron,photon,positron

INCIDENT ENERGY= spectrum          # monoenergetic, spectrum;
 SPEC FILENAME= C:\HEN_HOUSE\spectra\mohan6

SOURCE NUMBER= 1 # 0,1,2  :stop source inputs:


about spectra path, after  installing EGSnrc, spectra folder was in this path. I attach a pic to see my file path
Regards

    On Monday, November 26, 2018, 8:36:30 PM GMT+3:30, Reid Townson <notifications@github.com> wrote:  
 
 
It looks like you have mixed up the comments with the actual inputs. For example SPEC FILENAME= should be on its own line like it my example above. The text you pasted above is all mixed up, so try to clean it up, remove the comments if necessary, until it looks like my example.

Also, your path to the mohan6 file does not look correct, and it should have a file extension.

**Comment by rtownson** [comment] 2018-11-26 20:21
If that is the true path, it still needs a file extension (.spectrum).

**Comment by sahebeh** [comment] 2018-11-26 20:30
Dear Reid
Thanks a lotttttttttttttttttttttt. It work.I dont know how to thank you
Regards
    On Monday, November 26, 2018, 11:51:36 PM GMT+3:30, Reid Townson <notifications@github.com> wrote:  
 
 
If that is the true path, it still needs a file extension (.spectrum).
