### ISSUE TITLE
Error when defining geometry using the egs++ library

### ISSUE THREAD

**Issue by gwu-reflexionmedical** [nrc-cnrc/EGSnrc#105] opened 2016-06-09 17:10 UTC
I am writing a customized geometry to model a primary collimator in a linac system. The idea is model the collimator as a cylinder, and inscribe a collimated beam inside with medium of air. The shape of the beam, however, is not a regular pyramid, the left-right sides and the front-back sides form two virtual apexes. Virtual apex for the x-z plane is 10 mm above the target, but the virtual source for the y-z plane is 80 mm above the target. The shape will look like a pyramid truncated on the sides (not top-bottom sides).

egs_view has difficulty in understanding this kind of definition, and also popped out error saying `Failed to find a point that is inside the geometry`

My definition of the pyramid is attached. 
[collimator.txt](https://github.com/nrc-cnrc/EGSnrc/files/308028/collimator.txt)

**Comment by gwu-reflexionmedical** [comment] 2016-06-09 17:13
:start geometry definition:
    ################################# the planes
	:start geometry:
        library = egs_planes
        type    = EGS_Zplanes
        positions = 74 82
        name    = planeZ
    :stop geometry:
	
    ################################ the pyramid
    :start geometry:
        library = egs_pyramid
        type    = EGS_PyramidZ
        name    = pyramid
        points  = 20.6,1.2  20.6,-1.2 -20.6,-1.2 -20.6,1.2  \
				  20.6,1.2
        tip     = 0 0 92
    :stop geometry:

    ################################ the final geometry
    :start geometry:
        library = egs_ndgeometry
        name    = cut_pyramid1
        hownear method = 1
        dimensions = planeZ pyramid
		:start media input:
            media = W700ICRU
        :stop media input:
    :stop geometry:

	:start geometry:
        library = egs_planes
        type    = EGS_planes
        name    = planeT
        normals = 0,0.9999149,0.01304237
        positions = 1.1998979
    :stop geometry:
	
	:start geometry:
        library = egs_ndgeometry
        name    = cut_pyramid2
        hownear method = 0
        dimensions = planeT cut_pyramid1
    :stop geometry:
	
    simulation geometry = cut_pyramid2

:stop geometry definition:

:start view control:
  xmin = -0.5
  xmax =  0.5
  ymin = -0.5
  ymax =  0.5
  zmin =  72
  zmax =  84
:stop view control:

**Comment by mchamberland** [comment] 2016-06-09 22:00
Just for your information: GitHub is not the place for this type of issues. This area is restricted to reporting bugs in EGSnrc.

Your problem is not a bug with EGSnrc, but with your definition of the geometry. There are a couple of typos (`EGS_planes` should be `EGS_Planes`, `normals` should be `normal`) and I think you may have made a mistake in your pyramid definition (it does not have a flat rectangular base?). Also, double check that your second plane is correctly defined, especially the position. Finally, you forgot to define the medium in your last ND geometry. If you fix all of that, your geometry displays fine in egs_view.

**Comment by gwu-reflexionmedical** [comment] 2016-06-09 22:35
Hi Marc, I fixed the code based on your suggestion, and it still did not work. The error message said 
"Fail to find a point that is inside the geometry"

The pyramid has a flat base, which is defined by the EGS_Zplanes at z = 74 cm. I set the medium during the first cut (planeZ) but I guess I will need to set it again in every cut?

**Comment by mchamberland** [comment] 2016-06-09 23:31
Check your second plane again. Are you sure about its position?

**Comment by gwu-reflexionmedical** [comment] 2016-06-09 23:54
The position is correction.

I think what happened is egspp geometry package is sensitive to the normal of the plane. It only keeps the region in the normal direction. It seems like that I used the opposite normal. When I switched to negative normal with a negative position, the code works. 

I would suggest the author put this info in the online documentations. It might be somewhere in the 898 manual but no examples mention it

**Comment by mchamberland** [comment] 2016-06-10 00:01
Yes, this is all covers in PIRS 898: http://nrc-cnrc.github.io/EGSnrc/doc/pirs898/classEGS__PlanesT.html

**Comment by gwu-reflexionmedical** [comment] 2016-06-10 00:04
So there is one interesting question, what should the user do if they want to keep the other part using the plane, given EGSpp only takes one normal direction and keep the normal side of the object

**Comment by ftessier** [comment] 2016-07-29 14:13
Closing this issue as it is not cleary pointing to a bug in the egs++ library.

**Closed by ftessier** 2016-07-29 14:13 UTC
