### ISSUE TITLE
EGSnrc "g" application: lambda > lambdamax

### ISSUE THREAD

**Issue by DylanMK** [nrc-cnrc/EGSnrc#270] opened 2017-03-23 16:23 UTC
A warning message appears when attempting to gather values of mass-energy attenuation coefficient for energies above 1 MeV. On the other hand, this works just fine for energies equal or below to 1 MeV.

This error message is basically: `lambda > lambdamax`.

I have already posted about this issue on the Google+ forum:
https://plus.google.com/u/0/110361886935365433113/posts/7a7sM4cDdzZ?cfem=1

This has occurred to me while using the "g" usercode. I have tried:

- updating EGSnrc to the recent Feb 2017 release from the master branch
- updating my gcc compilers
- substracting the -ffast-math flags for the compilers

Is anyone else still experiencing similar difficulties?

**Comment by rtownson** [comment] 2017-03-23 16:52
How did you go about updating - was it a fresh install or did you use `git pull`? If you used `git pull` then you will need to copy the new `g` code to your `egs_home` and recompile.

For example:
```
cp $HEN_HOUSE/user_codes/g/g.mortran $EGS_HOME/g/
cd $EGS_HOME/g
make clean; make
```

**Comment by rtownson** [comment] 2017-03-24 12:55
@DylanMK if that doesn't work please provide the input file.

**Comment by DylanMK** [comment] 2017-03-24 13:27
I have attempted a fresh install, although I am not certain if I have successfully uninstalled EGSnrc before re-installing it, since it does not seem to appear as a package or software in bash/linux (ie dpkg --list).


Attached is a EGS input file for mean adipose tissue.


Thank you.



________________________________
De : Reid Townson <notifications@github.com>
Envoyé : vendredi 24 mars 2017 08:55:15
À : nrc-cnrc/EGSnrc
Cc : Dylan Mann-Krzisnik; Mention
Objet : Re: [nrc-cnrc/EGSnrc] "lambda > lambdamax" EGSnrc "g" (#270)


@DylanMK<https://github.com/DylanMK> if that doesn't work please provide the input file.

**Comment by ftessier** [comment] 2017-03-24 13:51
Please attach the file via the github issues interface, attachments don't survive via email reply.

**Comment by DylanMK** [comment] 2017-03-24 19:37
Here is the EGS input file for mean adipose tissue, as well as a screenshot of the g.mortran file, which contains neither of iausfl(34) = 1 nor iausfl(26).

Thank you
[adipose_egsinp.txt](https://github.com/nrc-cnrc/EGSnrc/files/868989/adipose_egsinp.txt)
![gmortran](https://cloud.githubusercontent.com/assets/26629493/24310831/ca8c51d4-10a7-11e7-9e0e-7b101f38d424.png)

**Comment by rtownson** [comment] 2017-03-25 18:35
Ok! This is an old version of `g`. It is important to note that there are copies of the user codes in each of the corresponding directories in `egs_home`. This idea here is that each user has her/his own egs_home where they can modify the codes. However, it does not get updated automatically when a new version of EGSnrc is installed (to protect your changes).

Either backup/remove your existing egs_home and let the installation script create a new one, or copy the new codes into the corresponding directories (see the example in my first comment).

Off-hand I can't remember, does the 'finalize for user' option in the installation script replace the codes in egs_home? This would be another option.

**Comment by DylanMK** [comment] 2017-03-29 23:35
After having copied the code for g.mortran with the command lines you have posted earlier (ie git -pull and cp command), I have the following g.mortran file (snapshot) which meets the requirement at line 713.

![gmortran2](https://cloud.githubusercontent.com/assets/26629493/24481025/c9dcb87a-14b5-11e7-8959-fce67b2759af.png)

For which other codes should this be done?

Otherwise, I have tried removing EGSnrc from my computer for a fresh install. Is simply deleting the files enough? I doubt it but couldn't figure out another way.

Thank you, this is truly appreciated.

**Comment by rtownson** [comment] 2017-03-30 13:13
Your version of `g` is now up to date! I will close this issue as I assume the problem is resolved.

To uninstall it is sufficient to completely remove `HEN_HOUSE` (and `egs_home`), or perhaps the directory containing `HEN_HOUSE` (EGSnrc?) if it is a git repository. There will also be some environment variables (in `~/.bashrc`) if you want to clean up completely.

All of the codes in `egs_home` must be replaced and recompiled after an update. We don't do this automatically because it would overwrite any changes the user made to the code. Instead of copying over the new codes you could entirely rename the old `egs_home` and then just copy over the *input files* you still need to the new `egs_home` the installation creates.

**Closed by rtownson** 2017-03-30 13:13 UTC
